micronaut:
  application:
    name: example-micronaut
datasources:
  default:
    url: jdbc:h2:mem:todo_db;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: henninb
    password: monday1
    schema-generate: CREATE_DROP
    dialect: H2
netty:
  default:
    allocator:
      max-order: 3
jpa.default.properties.hibernate.hbm2ddl.auto: update
